/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module3__Assessment;
import java.awt.Color;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Acer
 */
public class Threadss extends javax.swing.JFrame {
 private Thread thread;
    private Runs running = running = new Runs();
    private Random rand = new Random();
    private int MaxColorHue = 250;
   
    public Threadss() {
        initComponents();
    }
 public void ColorAnimation(){
 Nn.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 e.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 v.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 ee.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 r.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 g.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 i.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 vv.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 eee.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 u.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));
 p.setBackground(new Color(rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue), rand.nextInt(MaxColorHue)));

 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        e = new javax.swing.JLabel();
        Nn = new javax.swing.JLabel();
        v = new javax.swing.JLabel();
        vv = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        ee = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        u = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        eee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("STOP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        e.setBackground(new java.awt.Color(102, 153, 255));
        e.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e.setText("E");
        e.setOpaque(true);

        Nn.setBackground(new java.awt.Color(0, 255, 255));
        Nn.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 24)); // NOI18N
        Nn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nn.setText("N");
        Nn.setOpaque(true);

        v.setBackground(new java.awt.Color(51, 51, 255));
        v.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v.setText("V");
        v.setOpaque(true);

        vv.setBackground(new java.awt.Color(255, 102, 0));
        vv.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        vv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vv.setText("V");
        vv.setOpaque(true);

        r.setBackground(new java.awt.Color(204, 0, 255));
        r.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        r.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r.setText("R");
        r.setOpaque(true);

        i.setBackground(new java.awt.Color(255, 0, 51));
        i.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        i.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i.setText("I");
        i.setOpaque(true);

        ee.setBackground(new java.awt.Color(102, 51, 255));
        ee.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        ee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ee.setText("E");
        ee.setOpaque(true);

        g.setBackground(new java.awt.Color(255, 0, 153));
        g.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        g.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        g.setText("G");
        g.setOpaque(true);

        u.setBackground(new java.awt.Color(255, 255, 0));
        u.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        u.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u.setText("U");
        u.setOpaque(true);

        p.setBackground(new java.awt.Color(153, 255, 0));
        p.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        p.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p.setText("P");
        p.setOpaque(true);

        eee.setBackground(new java.awt.Color(255, 204, 0));
        eee.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 24)); // NOI18N
        eee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eee.setText("E");
        eee.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ee, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vv, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eee, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ee, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vv, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eee, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        thread = new Thread(running);
        thread.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
            if(thread.isAlive()){
                thread.stop();
            }else{
                System.out.println("Thread is stopped!");
            }
        } catch (Exception ex) {
            System.out.println("Thread is not started !");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Threadss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Threadss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Threadss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Threadss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Threadss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nn;
    private javax.swing.JLabel e;
    private javax.swing.JLabel ee;
    private javax.swing.JLabel eee;
    private javax.swing.JLabel g;
    private javax.swing.JLabel i;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p;
    private javax.swing.JLabel r;
    private javax.swing.JLabel u;
    private javax.swing.JLabel v;
    private javax.swing.JLabel vv;
    // End of variables declaration//GEN-END:variables
class Runs implements Runnable{
        
        @Override
        public void run() {
            try {
                while (true) {                    
                    Thread.sleep(1);
                   ColorAnimation();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        
    }
}
